name: "Vercel Deploy"
description: "Deploys to Vercel"
inputs:
  VERCEL_TOKEN:
    description: "Vercel API token"
    required: true
  MASTER_ALIAS:
    description: "URL to alias to when something is merged into master"
    required: true
  REPO_NAME:
    description: "The name of the repo the action is being ran in. Used to generate PR preview URLs"
    required: true
runs:
  using: "composite"
  steps:
    - name: "Install Vercel CLI"
      shell: bash
      run: npm install --global vercel
    - name: "Pull vercel info"
      shell: bash
      run: vercel pull --yes --environment=preview --token=${{ inputs.VERCEL_TOKEN }}
    - name: Mark pending
      uses: actions/github-script@v7
      with:
        script: |
          await github.rest.repos.createCommitStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            sha: context.sha,
            state: 'pending',
            context: 'vercel-deploy',
            description: 'Deployment in progress'
          })
    - name: "Build vercel"
      shell: bash
      run: vercel build --token=${{ inputs.VERCEL_TOKEN }}
    - name: "Deploy vercel"
      shell: bash
      id: deploy
      run: |
        set -euo pipefail
        DEPLOYMENT_URL="$(vercel deploy --prebuilt --archive=tgz --token=${{ inputs.VERCEL_TOKEN }})"
        echo "DEPLOYMENT_URL=$DEPLOYMENT_URL" >> "$GITHUB_OUTPUT"
    - name: Mark success
      uses: actions/github-script@v7
      with:
        script: |
          await github.rest.repos.createCommitStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            sha: context.sha,
            state: 'success',
            context: 'vercel-deploy',
            description: 'Vercel deployed',
            target_url: '${{ steps.deploy.outputs.DEPLOYMENT_URL }}'
          })
    - name: "Create alias"
      shell: bash
      id: "alias"
      run: |
        if [ ${{github.ref}} == 'refs/heads/master' ]; then
          ALIAS="${{ inputs.MASTER_ALIAS }}"
        else
          ALIAS="${{ inputs.REPO_NAME }}-${{ github.event.number }}.vercel.app"
        fi
        vercel alias --token=${{ inputs.VERCEL_TOKEN }} ${{ steps.deploy.outputs.DEPLOYMENT_URL }} $ALIAS
        echo "ALIAS=$ALIAS" >> "$GITHUB_OUTPUT"
    - name: "Update deploy status"
      uses: actions/github-script@v7
      with:
        script: |
          await github.rest.repos.createCommitStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            sha: context.sha,
            state: 'success',
            context: 'vercel-deploy',
            description: 'Vercel deployed and aliased',
            target_url: 'https://${{ steps.alias.outputs.ALIAS }}'
          })
    - name: Mark failure
      if: failure()
      uses: actions/github-script@v7
      with:
        script: |
          await github.rest.repos.createCommitStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            sha: context.sha,
            state: 'failure',
            context: 'vercel-deploy',
            description: 'Deployment failed'
          })
