name: Setup deploy environment
description: Sets up the deploy environment to allow running the internal CLI tools.
inputs:
  AWS_CLIENT_ID:
    description: AWS client ID
    required: true
  AWS_CLIENT_SECRET:
    description: AWS client secret
    required: true
  AWS_ECR_REPO:
    description: AWS ECR repository name for docker auth/login.
    required: true
  DOCKER_HUB_USERNAME:
    description: Docker Hub username used for registry login.
    required: true
  DOCKER_HUB_PASSWORD:
    description: Docker Hub password or access token used for registry login.
    required: true
  RELEASE_ROLE:
    description: AWS IAM role name to assume for release operations.
    required: true
  CI_GITHUB_TOKEN:
    description: GitHub token used to checkout the deploy repository.
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v6
      with:
        repository: NDLANO/deploy
        token: ${{ inputs.CI_GITHUB_TOKEN }}
        path: ndla/deploy

    - shell: bash
      run: ln -s ${{ github.workspace }}/ndla/deploy/mise.toml ${{ github.workspace }}/mise.toml

    - uses: jdx/mise-action@v3
      with:
        working_directory: ${{ github.workspace }}

    - uses: ndlano/reusable-workflows/.github/actions/setup-ndla-login@main
      with:
        AWS_CLIENT_ID: ${{ inputs.AWS_CLIENT_ID }}
        AWS_CLIENT_SECRET: ${{ inputs.AWS_CLIENT_SECRET }}
        AWS_ECR_REPO: ${{ inputs.AWS_ECR_REPO }}
        DOCKER_HUB_PASSWORD: ${{ inputs.DOCKER_HUB_PASSWORD }}
        DOCKER_HUB_USERNAME: ${{ inputs.DOCKER_HUB_USERNAME }}
        RELEASE_ROLE: ${{ inputs.RELEASE_ROLE }}

    - name: Install python dependencies
      shell: bash
      run: uv --directory $NDLA_DEPLOY sync --locked
