name: Login to NDLA repositories
inputs:
  AWS_CLIENT_ID:
    description: AWS client ID
    required: true
  AWS_CLIENT_SECRET:
    description: AWS client secret
    required: true
  AWS_ECR_REPO:
    description: AWS ECR repository name for docker auth/login.
    required: true
  DOCKER_HUB_USERNAME:
    description: Docker Hub username used for registry login.
    required: true
  DOCKER_HUB_PASSWORD:
    description: Docker Hub password or access token used for registry login.
    required: true
  RELEASE_ROLE:
    description: AWS IAM role name to assume for release operations.
    required: true

runs:
  using: composite
  steps:
    - name: Login to ECR repo
      shell: bash
      run: |
        RES=$(aws sts assume-role --role-arn ${{ inputs.RELEASE_ROLE }} --role-session-name github-actions-ecr-login)
        export AWS_ACCESS_KEY_ID=$(echo $RES | jq -r .Credentials.AccessKeyId)
        export AWS_SECRET_ACCESS_KEY=$(echo $RES | jq -r .Credentials.SecretAccessKey)
        export AWS_SESSION_TOKEN=$(echo $RES | jq -r .Credentials.SessionToken)
        aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin ${{ inputs.AWS_ECR_REPO }}
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.AWS_CLIENT_ID }}
        AWS_DEFAULT_REGION: eu-west-1
        AWS_SECRET_ACCESS_KEY: ${{ inputs.AWS_CLIENT_SECRET }}
    - name: Login to dockerhub
      shell: bash
      run: echo "${{ inputs.DOCKER_HUB_PASSWORD }}" | docker login --username "${{ inputs.DOCKER_HUB_USERNAME }}" --password-stdin
